# Generated by Django 3.1.6 on 2021-02-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfactor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='fl',
            new_name='file',
        ),
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default='dsa', max_length=100),
            preserve_default=False,
        ),
    ]
